---
- name: install postfix and dovecot loop
  hosts: rhel7
  become: true

  tasks:
    - name: loop install
      yum:
        name: {{ item }}
        state: present
        loop:
          - postfix
          - dovecot
      
