---
- name: Create a lvm
  hosts: rhel7

  tasks:
    - name: create partition
      parted:
        device: /dev/sdb
        number: 1
        flags: [lvm]
        state: present

    - name: create vg
      lvg:
        vg: vg-rhel
        pvs: /dev/sdb1
      #when: ansible_devices.sdb_partitions.sdb1 is defined

    - name: create lvm
      lvol:
        vg: vg-rhel
        lv: lv-rhel
        size: 1500m
      #when: ansible_lvm.vgs.vg-rhel is defined and ((ansible_lvm.vgs.vg-rhel.size_g|float)>1.5)

    - name: send message if volume group not large enough
      debug:
        msg: Not enough space for logical volume
      #when: ansible_lvm.vgs.vg-rhel is defined and ((ansible_lvm.vgs.vg-rhel.size_g|float)<1.5)

    - name: create a smaller logical volume
      lvol:
        vg: vg-rhel
        lv: lv-rhel
        size: 1500m
      #when: ansible_lvm.vgs.vg-rhel is defined and ((ansible_lvm.vgs.vg-rhel.size_g|float)<1.5)
    
    - name: create fs
      filesystem:
        dev: /dev/vg-rhel/lv-rhel
        fstype: xfs
      #when: ansible_lvm.vgs.vg-rhel is defined


      
