---
- name: Install standard software
  hosts: rhel7
  become: true
  tasks:
    - name: verify and install software
      yum:
        name: "{{ item }}"
        state: latest
      loop:
        - telnet
        - wget
        - curl
        - vim
        - lsof
        - nfs-utils
        - sg3_utils
