---
- name: Install standard software
  hosts: ubuntu
  become: true
  tasks:
    - name: verify and install software
      package:
        name: "{{ item }}"
        state: latest
      loop:
        - telnet
        - wget
        - curl
        - vim
